In [1]:
 # pip install numpy -> is the command for installing the numpy

In [3]:
import numpy as np

In [4]:
type(np.array([2,3,45,75,77]))

numpy.ndarray

In [5]:
np.arange(0,10) # work as same like range function in python

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [7]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [9]:
np.zeros ([4,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [10]:
np.ones(4)

array([1., 1., 1., 1.])

In [11]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [12]:
np.random.randint(0,30)

28

In [13]:
np.random.randint(0,1000,(4,5))

array([[491, 342, 251, 535, 887],
       [245, 509, 489, 663, 976],
       [452, 497, 493, 316, 932],
       [357,  93, 578, 971, 313]])

In [14]:
np.random.seed(101) # to get a fix random number in each time 
np.random.randint(0,100,10) 

array([95, 11, 81, 70, 63, 87, 75,  9, 77, 40])

In [15]:
arr=np.random.randint(0,100,10)

In [16]:
arr.max()

93

In [17]:
arr.min()

4

In [18]:
arr

array([ 4, 63, 40, 60, 92, 64,  5, 12, 93, 40])

In [19]:
arr.mean()

47.3

In [20]:
arr.argmax()

8

In [21]:
arr.argmin()

0

In [22]:
arr.reshape(2,5)

array([[ 4, 63, 40, 60, 92],
       [64,  5, 12, 93, 40]])

In [23]:
arr.reshape(4,4)

ValueError: cannot reshape array of size 10 into shape (4,4)

In [25]:
mat=np.arange(0,100).reshape(10,10)

mat

In [26]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [27]:
mat[0,0]

0

In [28]:
mat[0]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
mat[6][7]

67

In [33]:
mat[0,:]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
mat[:,0]

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [37]:
mat[0:3,0:3]

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22]])